module GithubMapping
  # §32-1: ticket_ledger → GitHub Issue の項目マッピング定義。
  # §29.2 / §30.4 で定義された必須項目を含む Issue 本文を構築する。
  class IssueBuilder
    LABEL_PREFIX = "ledger"

    def self.build(ticket)
      new(ticket).build
    end

    def initialize(ticket)
      @ticket = ticket
    end

    def build
      {
        title: title,
        body: body,
        labels: labels
      }
    end

    private

    attr_reader :ticket

    def title
      "[#{ticket.ticket_type}] #{ticket.title}"
    end

    def body
      <<~MD
        ## 台帳メタデータ
        | 項目 | 値 |
        |---|---|
        | ticket_id | #{ticket.id} |
        | ticket_type | #{ticket.ticket_type} |
        | scope_level | #{ticket.scope_level} |
        | service_id | #{ticket.service_id || 'N/A'} |
        | priority | #{ticket.priority} |
        | risk_level | #{ticket.risk_level || 'low'} |
        | status | #{ticket.status} |
        | due_date | #{ticket.due_date || 'N/A'} |
        | due_cycle | #{ticket.due_cycle || 'N/A'} |
        | assignee | #{ticket.assignee || 'N/A'} |

        ## linked_kpis
        #{format_kpis}

        ## linked_artifacts
        #{format_artifacts}

        ## 説明
        #{ticket.title}

        ---
        _Auto-generated by GithubMapping::IssueBuilder from ticket_ledger ##{ticket.id}_
      MD
    end

    def labels
      base = ["#{LABEL_PREFIX}:#{ticket.ticket_type}", "priority:#{ticket.priority}"]
      base << "scope:#{ticket.scope_level}"
      base << "risk:#{ticket.risk_level}" if ticket.risk_level.present?
      base << "service:#{ticket.service_id}" if ticket.service_id.present?
      base
    end

    def format_kpis
      Array(ticket.linked_kpis).map { |k| "- #{k}" }.join("\n").presence || "- なし"
    end

    def format_artifacts
      Array(ticket.linked_artifacts).map { |a| "- #{a}" }.join("\n").presence || "- なし"
    end
  end
end
