module GithubMapping
  # §32-1: ticket_ledger → GitHub PR 本文のマッピング定義。
  # §31 の必須項目（service_id / linked_kpis / source_ticket_id / risk_level /
  # docs_update_required / tech_record_update_required）を含む PR 本文を構築する。
  class PrBuilder
    def self.build(ticket, docs_update_required: false, tech_record_update_required: false)
      new(ticket, docs_update_required:, tech_record_update_required:).build
    end

    def initialize(ticket, docs_update_required: false, tech_record_update_required: false)
      @ticket = ticket
      @docs_update_required = docs_update_required
      @tech_record_update_required = tech_record_update_required
    end

    def build
      {
        title: title,
        body: body,
        labels: labels
      }
    end

    private

    attr_reader :ticket, :docs_update_required, :tech_record_update_required

    def title
      "[#{ticket.service_id || 'company'}] #{ticket.title}"
    end

    def body
      <<~MD
        ## 背景/目的
        ticket_ledger ##{ticket.id} に基づく実装。

        ## 変更内容
        #{ticket.title}

        ## §31 必須項目
        | 項目 | 値 |
        |---|---|
        | service_id | #{ticket.service_id || 'N/A'} |
        | linked_kpis | #{Array(ticket.linked_kpis).join(', ')} |
        | source_ticket_id | #{ticket.id} |
        | risk_level | #{ticket.risk_level || 'low'} |
        | docs_update_required | #{docs_update_required} |
        | tech_record_update_required | #{tech_record_update_required} |

        ## 受入条件（Acceptance Criteria）
        - [ ] ticket_ledger ##{ticket.id} の要件を満たす

        ## テスト
        - [ ] 関連するテストを追加/更新

        ## ロールアウト/デプロイ注意
        - risk_level: #{ticket.risk_level || 'low'}

        ## Ledger影響（台帳/Runner/定期実行）
        - source_meeting_type: #{ticket.source_meeting_type || 'N/A'}

        ## リスク & ロールバック
        - PR revert で戻せる

        ---
        _Auto-generated by GithubMapping::PrBuilder from ticket_ledger ##{ticket.id}_
      MD
    end

    def labels
      base = ["ticket:#{ticket.id}", "risk:#{ticket.risk_level || 'low'}"]
      base << "service:#{ticket.service_id}" if ticket.service_id.present?
      base
    end
  end
end
